baseURL = "https://hbapat.github.io/"
languageCode = "en"
title = "Harshavardhan Bapat"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "Harsha Bapat"
    description = "Finance, football and a bit of everything else"
    email = "harshavardhan.bapat@gmail.com"
    phone = "+1-248-854-1232"
    address = "414 W 44th St, #4C, New York, NY 10036"
    year = 2022
    avatar = "/images/me6.jpeg"
    avatarclass = "circle"
    background = ""
    banner = "/images/me4.jpeg"
    favicon = "/images/me2.jpeg"
    DateForm = "May 12, 2022"
    author = "Harshavardhan Bapat"

    showSubheader = true
    showServices = false
    showRecentWorks = true
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name= "Resume"
    url="/files/resume.pdf"
    weight = 5
[[menu.main]]
    name= "Poetry"
    url="/poetry/"
    weight = 6 

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/harshavardhan.bapat.5/"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/thebapat/"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/harshavardhan-bapat/"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/HBapat"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:harshavardhan.bapat@gmail.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"